### ISSUE TITLE
Convert Twitch API calls to Helix

### ISSUE THREAD

**Issue by Decicus** [Decicus/DecAPI#22]
Once Helix is in more of an... acceptable state (e.g. I still need subscriptions data), conversion to Helix should at the very least start. Luckily Helix allows us to get rid of a few things, but also requires to changes to other things.

Some endpoints (V3/V5) will eventually fail too, because of their [removal at the end of 2018](https://dev.twitch.tv/docs/v5#which-api-version-can-you-use). Either some alternatives have to be implemented, or just straight up removed with an error message (though I'd like to avoid the latter, if feasible somehow).

Other things to take into consideration:
1. Most endpoints seem to support a form of `user_login` (username) parameter, which should make the `cached_twitch_users` database table unnecessary (as I would no longer need to convert usernames to IDs before sending the request). The implementation for this was garbage in the first place, so that's just an improvement overall.
2. All channels (users) will need to re-authenticate for the subcount/points endpoints. The thing here though is that it will require both a V3/5 scope + a Helix scope. It might look weird on the authentication page, but considering the Helix scope for subscriptions isn't available yet, it's hard to tell.
3. This would be a good time to also refactor a lot of the code. I'm not happy with the current implementation of the API calls, and the format of the current Twitch API code is also not really... the way people would usually do it, I guess. Something should be done, though I haven't figured out what exactly I want to do.
4. Re-consider rate-limits, maybe? Luckily DecAPI has gotten a higher rate-limit (woohoo!) on Helix, which means that I can _maybe_ consider bumping up the rate-limit. With that said, not many users should ever *hit* that rate-limit and I've not seen many "legitimate" users do so, which means that this probably isn't necessary at all.

I'll update this list with more stuff once I have them all in my mind.

**Comment by Decicus** [comment]
Addition to point 1:
Not all endpoints support a form of `user_login`, though the main one that would require it is `/helix/streams` as the `/twitch/uptime` route is the one that sees the most requests.  
For the rest I can probably look up username => user IDs for every request and cache for say... 30 minutes? 60? Reset the 'timer' if the username is looked up again in those 30 minutes.

**Comment by Decicus** [comment]
~~Since Twitch [finally added the subscriber count to Helix](https://twitch.uservoice.com/forums/310213-developers/suggestions/37833286-add-subscriber-count-to-a-helix-endpoint), it's now possible to migrate `/twitch/subcount`.~~

Completed in #73

**Comment by Decicus** [comment]
~~They also added [emote-related API endpoints](https://discuss.dev.twitch.tv/t/announcing-api-endpoints-for-twitch-emotes/32073/). Alternative for the TwitchEmotes.com API for the endpoint `/twitch/subscriber_emotes`~~

Completed in commit f0ccd151c40871afbe7c90a42ba3e45e987cb6a0

**Comment by Decicus** [comment]
Twitch has now announced [a set date for the removal of V5](https://blog.twitch.tv/en/2021/07/15/legacy-twitch-api-v5-shutdown-details-and-timeline/).

There are quite a few endpoints that need to be migrated, but some of them may need to be deprecated/removed (or should be deprecated/removed due to lack of use).
- [x] `accountage` - Completed in #73 
- [x] `creation` - Completed in #73 
- [x] `followage` - See #75 
- [x] `followers` - See #75 
- [x] `following` - See #75 
- [x] `highlight` - See #75 
- [x] `highlightRandom`
- [x] ~~`latest_sub`~~ / `random_sub` (same function) - Random sub is updated in #80 - Latest sub has been deprecated as Helix does not provide timestamps for subscribers (same as `subage`).
- [x] ~~`subage` (I kind of want to remove/deprecate this one - as it's generally incorrect)~~ - Helix does not provide any information in regards to "subscription created date", therefore this has been deprecated. See #80 
- [x] `subcount` - Completed in #73 
- [x] `team_members` - Added in #80 
- [x] ~~`upload` - might not even be in use tbh, are twitch uploads a thing anymore? 🙃~~ - Deprecated, see #75 
- [x] `viewercount` - Completed in 0554044
- [x] `videos` - See #80 
- [x] `vod_replay` - See #80

**Comment by Decicus** [comment]
~~`/twitch/subpoints` can now be changed to not 'calculate' the points and instead get it directly from Helix: https://twitter.com/TwitchDev/status/1444071978697175046?s=19~~

Completed in #73
